services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://root:password_karomah@mongodb:27017/karomah?authSource=admin
      - JWT_SECRET=${JWT_SECRET:-karomah_secret_key_123}
    depends_on:
      - mongodb
    restart: always
    volumes:
      - app-uploads:/app/public/uploads

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password_karomah
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
  app-uploads:
